apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"debug","service":"debug"},"name":"debug","namespace":"default"},"spec":{"ports":[{"name":"http","port":80}],"selector":{"app":"debug"}}}
  creationTimestamp: "2021-09-03T20:07:41Z"
  labels:
    app: debug
    service: debug
  name: debug
  namespace: default
  resourceVersion: "108170"
  uid: 72b1b443-3038-4f83-8601-3bbf375931aa
spec:
  clusterIP: 10.97.127.233
  clusterIPs:
  - 10.97.127.233
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: debug
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
